Fixing missing tkinter Error
I ran into this problem on Fedora 38 beta

```
 $ ./quadplay 
Traceback (most recent call last):
  File "/home/erik/Downloads/quadplay-main/tools/quadplay-server.py", line 58, in <module>
    import os, time, platform, sys, threading, socket, argparse, multiprocessing, json, ssl, codecs, glob, shutil, re, base64, random, getpass, inspect, subprocess, workjson, signal, shlex, tkinter, tkinter.messagebox, urllib, urllib.request
ModuleNotFoundError: No module named 'tkinter'
```